- name: Update apt cache
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker.io
    state: present

- name: Install docker compose plugin
  apt:
    name: docker-compose-plugin
    state: present

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
