name: Deploy Dev

on:
  workflow_dispatch:


jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init (dev)
      working-directory: terraform/dev
      run: terraform init

    - name: Terraform validate
      working-directory: terraform/dev
      run: terraform validate
